name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, label-go]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: build client
      run: |
        cd client-repo
        pwd
        cd ../../../../../
        pwd
        ls
        cd community_page
        ls
        cd client-repo
        ls
        git status
#        npm install
#        npm run build:prod
#    - name: build server
#      run : |
#        cd ../server-repo
#        npm install
#    - name: run pm2
#      run: |
#        pm2 start ecosystem.config.js
#        cd ../client-repo
#        pm2 start ecosystem.config.js
