name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, label-go]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: git pull
      run: mkdir test1
