name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PEM_KEY }}
          host: ip-172-31-15-87.ap-northeast-2.compute.internal
          username: ubuntu
          port: 22
          script: cd server_repo || npm run build:prod 
