name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PEM_KEY }}
          host: "ec2-52-79-176-146.ap-northeast-2.compute.amazonaws.com"
          username: ubuntu
          port: 22
          script: whoami
